services:
  main-container:
    build: .
    container_name: main-container
    command:
    - "-host"
    - "main-container"
    - "-agents"
    - "recepcionistaAgent:edu.sma.agents.RecepcionistaAgent;floristaAgent:edu.sma.agents.FloristaAgent"
    ports:
      - "1099:1099"
    networks:
      - jade-net

  peripheral-container:
    build: .
    container_name: peripheral-container
    command:
      - "-container"
      - "-host"
      - "main-container"
      - "-port"
      - "1099"
      - "-agents"
      - "novio1:edu.sma.agents.NovioAgent(1,Matias);novio2:edu.sma.agents.NovioAgent(2,Alejandro);novio3:edu.sma.agents.NovioAgent(3,Luigi)"
    depends_on:
      - main-container
    networks:
      - jade-net
networks:
  jade-net:
    driver: bridge