services:
  main-container:
    build: .
    container_name: main-container
    command:
      - "-name"
      - "FLORERIA"
      - "-local-host"
      - "main-container"
      - "-local-port"
      - "1099"
      - "-mtp"
      - "jade.mtp.http.MessageTransportProtocol(http://main-container:7778/acc)"
      - "recepcionista:edu.sma.agents.RecepcionistaAgent;florista:edu.sma.agents.FloristaAgent"
    ports:
      - "1099:1099"
      - "7778:7778"
    networks:
      - jade-net

  peripheral-container:
    build: .
    container_name: peripheral-container
    command:
      - "-container"
      - "-host"
      - "main-container"
      - "-port"
      - "1099"
      - "novio1:edu.sma.agents.NovioAgent(Carlos,1);novio2:edu.sma.agents.NovioAgent(Miguel,2);novio3:edu.sma.agents.NovioAgent(Javier,3)"
    depends_on:
      - main-container
    networks:
      - jade-net

networks:
  jade-net:
    driver: bridge
